-- Seed pool rotativo de keywords (250 más importantes)
INSERT INTO keywords (keyword, category) VALUES
-- Languages (20)
('javascript', 'language'),
('typescript', 'language'),
('python', 'language'),
('go', 'language'),
('rust', 'language'),
('java', 'language'),
('kotlin', 'language'),
('swift', 'language'),
('cpp', 'language'),
('c', 'language'),
('csharp', 'language'),
('ruby', 'language'),
('php', 'language'),
('dart', 'language'),
('lua', 'language'),
('zig', 'language'),
('bash', 'language'),
('r', 'language'),
('julia', 'language'),
('scala', 'language'),

-- Frontend (25)
('react', 'frontend'),
('vue', 'frontend'),
('angular', 'frontend'),
('svelte', 'frontend'),
('solidjs', 'frontend'),
('preact', 'frontend'),
('htmx', 'frontend'),
('alpinejs', 'frontend'),
('nextjs', 'frontend'),
('nuxt', 'frontend'),
('astro', 'frontend'),
('remix', 'frontend'),
('tailwindcss', 'frontend'),
('bootstrap', 'frontend'),
('material-ui', 'frontend'),
('shadcn-ui', 'frontend'),
('radix-ui', 'frontend'),
('ant-design', 'frontend'),
('styled-components', 'frontend'),
('sass', 'frontend'),
('postcss', 'frontend'),
('zustand', 'frontend'),
('pinia', 'frontend'),
('storybook', 'frontend'),
('docusaurus', 'frontend'),

-- Backend (25)
('express', 'backend'),
('fastify', 'backend'),
('koa', 'backend'),
('hapi', 'backend'),
('nestjs', 'backend'),
('spring-boot', 'backend'),
('django', 'backend'),
('flask', 'backend'),
('fastapi', 'backend'),
('gin', 'backend'),
('fiber', 'backend'),
('actix-web', 'backend'),
('rocket', 'backend'),
('axum', 'backend'),
('rails', 'backend'),
('laravel', 'backend'),
('symfony', 'backend'),
('phoenix', 'backend'),
('graphql', 'backend'),
('trpc', 'backend'),
('grpc', 'backend'),
('socket.io', 'backend'),
('hasura', 'backend'),
('supabase', 'backend'),
('micronaut', 'backend'),

-- AI/ML (30)
('tensorflow', 'ai-ml'),
('pytorch', 'ai-ml'),
('keras', 'ai-ml'),
('huggingface', 'ai-ml'),
('transformers', 'ai-ml'),
('langchain', 'ai-ml'),
('llama-index', 'ai-ml'),
('openai', 'ai-ml'),
('ollama', 'ai-ml'),
('stable-diffusion', 'ai-ml'),
('whisper', 'ai-ml'),
('opencv', 'ai-ml'),
('yolo', 'ai-ml'),
('scikit-learn', 'ai-ml'),
('pandas', 'ai-ml'),
('numpy', 'ai-ml'),
('xgboost', 'ai-ml'),
('lightgbm', 'ai-ml'),
('jax', 'ai-ml'),
('ray', 'ai-ml'),
('mlflow', 'ai-ml'),
('kubeflow', 'ai-ml'),
('chroma', 'ai-ml'),
('weaviate', 'ai-ml'),
('qdrant', 'ai-ml'),
('mistral', 'ai-ml'),
('deepseek', 'ai-ml'),
('vllm', 'ai-ml'),
('llama-cpp', 'ai-ml'),
('comfyui', 'ai-ml'),

-- Databases (18)
('postgresql', 'database'),
('mysql', 'database'),
('sqlite', 'database'),
('mongodb', 'database'),
('redis', 'database'),
('elasticsearch', 'database'),
('clickhouse', 'database'),
('cockroachdb', 'database'),
('timescaledb', 'database'),
('influxdb', 'database'),
('neo4j', 'database'),
('planetscale', 'database'),
('neon', 'database'),
('turso', 'database'),
('meilisearch', 'database'),
('prisma', 'database'),
('drizzle', 'database'),
('valkey', 'database'),

-- DevOps (30)
('kubernetes', 'devops'),
('docker', 'devops'),
('podman', 'devops'),
('terraform', 'devops'),
('opentofu', 'devops'),
('pulumi', 'devops'),
('ansible', 'devops'),
('helm', 'devops'),
('kustomize', 'devops'),
('istio', 'devops'),
('nginx', 'devops'),
('caddy', 'devops'),
('traefik', 'devops'),
('prometheus', 'devops'),
('grafana', 'devops'),
('loki', 'devops'),
('tempo', 'devops'),
('opentelemetry', 'devops'),
('jaeger', 'devops'),
('sentry', 'devops'),
('github-actions', 'devops'),
('gitlab-ci', 'devops'),
('jenkins', 'devops'),
('argo', 'devops'),
('flux', 'devops'),
('vault', 'devops'),
('consul', 'devops'),
('packer', 'devops'),
('vagrant', 'devops'),
('crossplane', 'devops'),

-- Mobile/Desktop (8)
('flutter', 'mobile'),
('react-native', 'mobile'),
('expo', 'mobile'),
('electron', 'desktop'),
('tauri', 'desktop'),
('swiftui', 'mobile'),
('jetpack-compose', 'mobile'),
('kotlin-multiplatform', 'mobile'),

-- Tools (20)
('vite', 'tools'),
('webpack', 'tools'),
('esbuild', 'tools'),
('rollup', 'tools'),
('bun', 'tools'),
('swc', 'tools'),
('babel', 'tools'),
('eslint', 'tools'),
('prettier', 'tools'),
('pnpm', 'tools'),
('yarn', 'tools'),
('nx', 'tools'),
('turborepo', 'tools'),
('zod', 'tools'),
('sharp', 'tools'),
('puppeteer', 'tools'),
('playwright', 'tools'),
('tsx', 'tools'),
('dayjs', 'tools'),
('swr', 'tools'),

-- Testing (8)
('jest', 'testing'),
('vitest', 'testing'),
('cypress', 'testing'),
('testing-library', 'testing'),
('mocha', 'testing'),
('jasmine', 'testing'),
('k6', 'testing'),
('playwright', 'testing'),

-- Data (18)
('kafka', 'data'),
('apache-spark', 'data'),
('apache-flink', 'data'),
('apache-airflow', 'data'),
('dbt', 'data'),
('dagster', 'data'),
('prefect', 'data'),
('duckdb', 'data'),
('polars', 'data'),
('delta-lake', 'data'),
('iceberg', 'data'),
('trino', 'data'),
('metabase', 'data'),
('superset', 'data'),
('great-expectations', 'data'),
('debezium', 'data'),
('kafka-connect', 'data'),
('datahub', 'data'),

-- Blockchain (5)
('ethereum', 'blockchain'),
('solana', 'blockchain'),
('hardhat', 'blockchain'),
('foundry', 'blockchain'),
('openzeppelin', 'blockchain'),

-- Game Dev (5)
('godot', 'gamedev'),
('unity', 'gamedev'),
('bevy', 'gamedev'),
('raylib', 'gamedev'),
('threejs', 'gamedev'),

-- General (10)
('webassembly', 'general'),
('webgpu', 'general'),
('ebpf', 'general'),
('llm', 'general'),
('rag', 'general'),
('agent', 'general'),
('vector-database', 'general'),
('cybersecurity', 'general'),
('neovim', 'general'),
('distributed-systems', 'general'),
('docker-compose', 'devops'),
('systemd', 'devops'),
('biome', 'tools'),
('ruff', 'tools'),
('sqlc', 'tools'),
('obsidian', 'tools'),
('elixir', 'language'),
('clojure', 'language'),
('haskell', 'language'),
('erlang', 'language'),
('nim', 'language'),
('lit', 'frontend'),
('aiohttp', 'backend'),
('echo', 'backend'),
('typeorm', 'database'),
('dgraph', 'database'),
('opensearch', 'database'),
('typesense', 'database'),
('kind', 'devops'),
('minikube', 'devops'),
('k3s', 'devops'),
('husky', 'tools'),
('lint-staged', 'tools'),
('rxjs', 'tools'),
('capacitor', 'mobile'),
('materialize', 'data'),
('selenium', 'testing'),
('karma', 'testing'),
('playcanvas', 'gamedev')
ON CONFLICT (keyword) DO NOTHING;
